[env:rp2040]
platform = raspberrypi
board = rpipico
framework = arduino
monitor_speed = 115200
monitor_echo = yes

build_flags =
    -D PICO_DVI
    -D PICO_CORE1_STACK_SIZE=4096
    -O2

lib_deps =
    https://github.com/wren6991/PicoDVI.git
    https://github.com/earlephilhower/arduino-pico.git
    SdFat
