[env:rp2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower

monitor_speed = 115200
upload_protocol = picotool
upload_speed = 921600

lib_deps =
    https://github.com/sparkfun/SparkFun_PicoDVI_Arduino_Library.git

build_flags = -O2